# Generated by Django 4.0.10 on 2024-05-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
