# Generated by Django 4.0.10 on 2024-05-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
