# Generated by Django 4.0.10 on 2024-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_profile_bio_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learning_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='learning_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='learning_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lesson_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
